fix staticcheck errors
pkg/scraper/url.go:112:15: error strings should not be capitalized (ST1005)
pkg/scraper/url.go:238:6: func cdpNetwork is unused (U1000)